import Head from 'next/head'
import Layout from '../components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/Untitled design (1).png";
import AnimatedText from '../components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from './../components/Icons';
import HireMe from '../components/HireMe'
import crane from '../../public/images/svgs/crane.svg'
import TransitionEffect from '../components/TransitionEffect';
import Form from '../components/Form'


export default function Home() {
  return (
    <>
      <Head>
        <title>SIPL | INDIA'S TOP CONTRUCTION COMPANY | AGENT </title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <TransitionEffect />

      <main className='flex item-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8'>
          <div className='flex items-center justify-between w-full lg:flex-col'>
            <div className='w-1/2 md:w-full'>
              <Image src={profilePic} alt="SIPL" className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes='(max-width: 768px) 100vw,
              (max:width: 1200px) 50vw,
              50vw'
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center capitalize'>
              <AnimatedText text="Turning Vision Into Reality With " className='!text-3xl !text-left
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              ' />
              <AnimatedText text="Shrinet infrastructure" className='!text-6xl !text-left
              xl:!text-1xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl ' />

              <AnimatedText text="private limited" className='!text-3xl !text-left
              xl:!text-1xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' />

              <div className='my-4 text-base md:text-sm sm:text-xs !font-bold text-red-950 dark:text-sec'>
                * Redefining real estate, one brick at a time.<br />
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs text-black dark:text-white'>
                  Pioneering the future of real estate with cutting-edge construction and comprehensive property solutions.
                </p>
                * Your dream home, delivered.<br />
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs text-black dark:text-white'>
                  Empowering clients with innovative, sustainable choices and unparalleled real estate expertise.
                </p>
                * Building more than just structures, building relationships.
                <p className='my-4 text-base font-medium md:text-sm sm:text-xs text-black dark:text-white'>
                  Crafting spaces that inspire, built on a foundation of trust and transparency.
                </p>
              </div>
              <div className='flex items-center self-start mt-2 lg:self-center'>
                <Link href="/profile.pdf" target={'_blank'}
                  className='flex items-center bg-dark text-light px-6 py-2.5 rounded-lg text-lg font-semibold   
                         hover:bg-light hover:text-dark 
                         border-2 border-solid border-transparent hover:border-dark

                         dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light 
                         hover:dark:border-light md:p-2 md:px-4 md:text-base
                         '
                download={true}
                >portfolio <LinkArrow className={"w-6 ml-1"} />

                </Link>
                <Link href="/contact"
                  className='ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base'
                >Contact</Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />

        <div className='absolute right-8 bottom-8 inline-block w-32  md:hidden'>
          <Image src={crane} alt="crane" className='w-full h-auto' />
        </div>
      </main>



      <div className="flex items-center justify-center w-full h-auto space-x-8 md:space-x-4 rounded-2xl ">


        {/* Projects Button */}
        <Link
          href="/projects"
          className='relative flex items-center justify-center bg-dark text-light w-[33vw] h-[33vh] sm:w-[22vh] sm:h-[22vh] sm:ml-2
       hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
       dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light 
       hover:dark:border-light md:p-4 md:text-base rounded-2xl'
        >
          <div
            className='absolute top-0 right-0 bottom-0 left-0 bg-cover bg-center rounded-2xl'
            style={{ backgroundImage: `url('/images/project.jpg')` }}
          ></div>
          <span className='absolute left-0 top-0 w-full h-full bg-opacity-50 bg-gray-500 rounded-2xl z-15'></span>
          <span className='relative z-20 text-4xl sm:text-2xl md:text-3xl lg:text-4xl font-semibold'>Projects</span>
        </Link>

        {/* Inventory Button */}
        <Link
          href="/articles"
          className='relative flex items-center justify-center bg-dark text-light w-[33vw] h-[33vh] sm:w-[22vh] sm:h-[22vh] sm:mr-2
       hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
       dark:text-dark dark:bg-light hover:dark:bg-dark hover:dark:text-light 
       hover:dark:border-light md:p-4 md:text-base rounded-2xl'
        >
          <div
            className='absolute top-0 right-0 bottom-0 left-0 bg-cover bg-center rounded-2xl z-0'
            style={{ backgroundImage: `url('/images/inventory.jpg')` }}
          ></div>
          <span className='absolute left-0 top-0 w-full h-full bg-opacity-50 bg-gray-500 rounded-2xl z-10'></span>
          <span className='relative z-20 text-4xl sm:text-2xl md:text-3xl lg:text-4xl font-semibold'>Inventory</span>
        </Link>



      </div>

      <div className="py-8 flex flex-col items-center justify-center lg:flex-col lg:py-6" >


        <div className='p-4 text-3xl dark:text-light m-6 lg:!text-center lg:!text-3xl md:!text-2xl sm:!text-xl'>
          “Join our community and unlock exclusive tips, updates on our latest offerings, and a chance to connect with like-minded individuals!”</div>

        <Form />

      </div>

    </>
  )
}
